# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

# Not ideal to use the same database, but trying to keep this as siimple as possible
cache:
  <<: *default
  database: <%= ENV.fetch("DATABASE_URL", "storage/#{Rails.env}.sqlite3") %>

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>
